"""empty message

Revision ID: 36dc86bf75c4
Revises: 35dc2511af2f
Create Date: 2013-11-05 13:30:40.466301

"""

# revision identifiers, used by Alembic.
revision = '36dc86bf75c4'
down_revision = '35dc2511af2f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=64), nullable=True),
    sa.Column('student_points', sa.Integer(), nullable=True),
    sa.Column('info', sa.String(length=5012), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    ### end Alembic commands ###
