"""empty message

Revision ID: 43cfebde8c
Revises: 58fb058b62ae
Create Date: 2013-10-31 17:24:07.232535

"""

# revision identifiers, used by Alembic.
revision = '43cfebde8c'
down_revision = '58fb058b62ae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('passwd', sa.String(length=512), nullable=True))
    op.add_column('user', sa.Column('url', sa.String(length=64), nullable=True))
    op.drop_column('user', u'login')
    op.drop_column('user', u'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(u'password', sa.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column(u'login', sa.VARCHAR(length=80), nullable=True))
    op.drop_column('user', 'url')
    op.drop_column('user', 'passwd')
    op.drop_column('user', 'name')
    op.drop_column('user', 'date_created')
    ### end Alembic commands ###
